# Generated by Django 2.0.2 on 2018-02-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20180211_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='iso',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
